version: '3.8'

services:
  # 1. MONGODB DATABASE CONTAINER
  mongodb:
    image: mongo:latest
    container_name: ecom_mongo
    ports:
      - "27017:27017" # Maps container port to localhost port
    volumes:
      - mongo_data:/data/db # Prevents data deletion when container stops

  # 2. REDIS CACHE CONTAINER
  redis:
    image: redis:alpine
    container_name: ecom_redis
    ports:
      - "6379:6379"

  # 3. EXPRESS.JS BACKEND CONTAINER
  backend:
    build: .
    container_name: ecom_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules from overriding container node_modules
      - ./public/uploads:/app/public/uploads
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecomsphere
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis


# Allocate persistent memory volume for MongoDB
volumes:
  mongo_data:
